# Generated by Django 6.1.2 on 2026-10-09 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='analyses/%Y/%m/')),
                ('predicted_class', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_scores', models.JSONField(blank=True, help_text='Raw logits or probabilities', null=True)),
                ('model_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inference_duration', models.FloatField(blank=True, help_text='Inference time in seconds', null=True)),
                ('image_metadata', models.JSONField(blank=True, help_text='EXIF and format details', null=True)),
                ('error_category', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Optional associate user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
